server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL8 驱动（必须带 cj）
    url: jdbc:mysql://192.168.0.200:3306/bugucloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:   # 自带HikariCP连接池配置
      maximum-pool-size: 10  # 最大连接数
      minimum-idle: 5       # 最小空闲连接
      idle-timeout: 30000   # 空闲超时时间
  data:
    redis:
      host: 192.168.0.200
      port: 6379
      password: 123456
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 16        # 最大连接数
          max-idle: 8           # 最大空闲连接
          min-idle: 4           # 最小空闲连接
          max-wait: 2000ms      # 获取连接的最大等待时间
        shutdown-timeout: 100ms # 关闭超时


knife4j:
  enable: true               # 开启增强功能
  production: false          # 生产环境设为 true（关闭文档）
  setting:
    language: zh-CN          # 中文界面
springdoc:
  api-docs:
    enabled: true            # 开启 OpenAPI 文档生成
